# Generated by Django 4.2.5 on 2024-02-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=66)),
                ('destination', models.CharField(max_length=66)),
                ('duriation', models.IntegerField()),
            ],
        ),
    ]
